### ISSUE TITLE
Issues overriding previewRenderer for textmedia, text, textpic and images

### ISSUE THREAD

**Issue by kimchristiansen** [b13/backendpreviews#19]
I have just tried your fabulous extension on an TYPO3 v12 installation. Great extension, as always! It just took me a little longer to find out why I can't overwrite the backend previews of the following ctypes: text, textmedia, textpic and images. 

The reason is that in the TCA 
`
vendor/typo3/cms-frontend/Configuration/TCA/tt_content.php explicit previewRenderers 
`
are assigned to these ctypes:
`
'previewRenderer' => \TYPO3\CMS\Frontend\Preview\TextPreviewRenderer::class
`

I therefore had to explicitly overwrite the previewRenderer for these ctypes:
`
// override textmedia previewRenderer
$GLOBALS['TCA']['tt_content']['types']['textmedia']['previewRenderer'] = \B13\Backendpreviews\Backend\Preview\StandardContentPreviewRenderer::class;
`

Is this the right way, or have I overlooked something?

**Comment by davidsteeb** [comment]
Hi @kimchristiansen thank you for reporting this, I updated the README file accordingly.

**Comment by kimchristiansen** [comment]
Great, thank you!
